### ISSUE TITLE
Interrupt breaks the crete_pre/crete_post order assertion

### ISSUE THREAD

**Issue by moralismercatus** [SVL-PSU/crete-dev#41] opened 2017-12-12 01:30 UTC
**Background**
While running crete-qemu either with GDB remote debugging, or in a pre-boot environment (e.g., BIOS), the sanity check assertion is raised:

https://github.com/moralismercatus/crete-dev/blob/master/front-end/qemu-2.3/runtime-dump/runtime-dump.cpp#L1856-L1860

Based on our analysis, the cause is essentially that CRETE expects TB execution to follow the the flow:

```
for(;;)
  sigsetjmp();
  ...
  crete_pre_cpu__tb_exec();
  cpu_tb_exec();
  crete_post_cpu_tb_exec();
```

Interrupts can occur within cpu_tb_exec() which call cpu_loop_exit(). This function performs a siglongjmp() to the sigsetjmp() at the top of the loop, thus breaking the pre/post flow.

**Reproducing**
To reproduce, simply run crete-qemu under gdb, and single step e.g.,:

```
# Start CRETE in a suspended state (-S) and with remote debugging enabled (-s):
crete-qemu-2.3-system-x86_64 -m 128 -s -S &
# Start gdb:
gdb
# Within gdb, attach to QEMU and begin single stepping:
target remote localhost:1234
si
si
# Assertion will appear here!
```

**Specs**
Commit used: 71ab5f8f3c6116e1024219d6b93190102c956584
Also confirmed on latest from SVL-PSU/master.

**PS**
The nature of single stepping is interrupt-driven, which is why this remote debugging will reproduce the problem.

**Comment by likebreath** [comment] 2017-12-12 20:25
@moralismercatus @zhenkun Thanks for summarizing and reporting this issue to me. I can reproduce it through "gdb remote debugging with QEMU".

Few comments and initial thoughts about the description of this issue.  

1. I think you mean "To reproduce, simply run crete-qemu with option '-s' and step instruction in remote gdb". The option "-s" of qemu opens an interface for a remote gdb to debug code running on top of QEMU's virtual CPU (such as OS kernel code and BIOS code running inside QEMU). It is totally different from debugging QEMU itself with GDB, which was my original interpretation of  " run crete-qemu under gdb".

2. You are right about the general cause of the issue. This failed assertion is a guard to assure one of the main assumptions crete-tracer made, crete_pre/post_cpu_tb_exec should always be paired up. Various interrupts are now handled by crete-tracer with '[crete_handle_raise_interrupt()](https://github.com/likebreath/crete-dev/blob/a226c245f51347b88ba9a95448a694bf1997a080/front-end/qemu-2.3/runtime-dump/runtime-dump.cpp#L2187)' and '[crete_handle_do_interrupt_all()](https://github.com/likebreath/crete-dev/blob/a226c245f51347b88ba9a95448a694bf1997a080/front-end/qemu-2.3/runtime-dump/runtime-dump.cpp#L2227)'.

3. The interrupt handling is certainly not complete, at least the option "-s" with step instruction breaks it. My feeling is option "-s"  changes qemu's flow of emulating guest instructions, which can be very different from the normal emulation flow (which is more similar to the native execution flow  on real machines).  There is a chance "-s" breaks this assertion in a different way as how your original running example of BIOS breaks it.  This is why I would like to double check whether this is a good working example to solve your problem. We should find a time to talk about more details.

Please let me know your thoughts. Thanks.

**Comment by likebreath** [comment] 2017-12-12 21:53
With some debugging, I located the reason why the assertion fails with "step instruction".

With "step instruction", single step mode is [enabled](https://github.com/SVL-PSU/crete-dev/blob/f55610717a451ff770156611f2a7e7d40b42760b/front-end/qemu-2.3/gdbstub.c#L866) for virtual CPU, which [forces calls ](https://github.com/SVL-PSU/crete-dev/blob/a226c245f51347b88ba9a95448a694bf1997a080/front-end/qemu-2.3/target-i386/translate.c#L2597)into a special helper "helper_debug()" after executing each TB (the unit of emulating guest instructions in QEMU). This [helper function](https://github.com/SVL-PSU/crete-dev/blob/b88add3f6db504bb94555af2df727ad7406520c0/front-end/qemu-2.3/target-i386/misc_helper.c#L641) sets the special debug flag "EXCP_DEBUG" and exits the execution loop with "cpu_loop_exit()". As crete-tracer is not ware of this special function, the pre-exec-post chain was broken and the assertion failed.

Interrupt handling of crete-tracer was designed to deal with "real" interrupts from software or hardware. This special helper function is less like a "real" interrupt. It is more like a VM-level special execution flow control, and is certainly QEMU implementation dependent. 

Special handling for this helper function (or other related ones) can be added to solve the assertion failure. But I am not sure whether your running example are caused by the same reason. We should double check. Please let me know your thoughts. @moralismercatus @zhenkun

**Comment by moralismercatus** [comment] 2017-12-12 22:22
Hi @likebreath . Thanks for taking the time to do this. We were also encountering the same assertion under other conditions that we have since learned are because _env->eip == 0_ which was triggering some kind of interrupt. On that account, the severity for us doesn't seem as urgent as first thought.

It would be nice to be able to remote debug, but, so long as we don't encounter this during normal execution, it may be acceptable for the time being.

Thanks,

**Comment by likebreath** [comment] 2017-12-12 22:43
@moralismercatus Can you provide more details about the assertion you encountered with "env->eip == 0"? Like how does the interrupt you mentioned call into "cpu_loop_exit()" (a backtrace from gdb should tells you that)? We can do pair debugging if you can't share the example with me.

Also, is there a special reason why you would like to use remote debug with crete-qemu? It seems to be cleaner to separate debugging on BIOS (with native qemu) and tracing on BIOS (with crete-qemu).

**Comment by moralismercatus** [comment] 2017-12-13 20:16
@likebreath 

I misspoke. It's actually a different assertion that I encounter when _eip == 0_. Here is a sample output:
```
eip: ...
eip: ffd8a286
eip: ffd8a2a1
eip: 0
crete-qemu-2.3-system-x86_64: front-end/qemu-2.3/runtime-dump/runtime-dump.cpp:2224: void crete_handle_do_interrupt_all(void*, int, int, int, uint64_t, int): Assertion `is_hw' failed.
```
This is of lesser importance, as eip shouldn't have been 0 anyway. In short, it arose from an incorrect stack in which the contents of the stack were all 0s, so the _ret_ instruction yielded an eip of 0.

Yes, there is a special reason we would like to use gdb remote debugging. It provides a convenient interface for single stepping through the code and examining register contents. This is actually important for us to be done while CRETE is tracing, for our particular application of CRETE, if possible.

Assume for the time being, that there is a reasonable desire for this capability.

What do you think?

Thanks,

**Comment by likebreath** [comment] 2018-01-04 20:27
A fix has been made. Please re-open if new problems occur.

**Closed as completed by likebreath** 2018-01-04 20:27 UTC
