### ISSUE TITLE
Bottleneck of transmitting trace from vm-node to dispatch

### ISSUE THREAD

**Issue by likebreath** [SVL-PSU/crete-dev#34] opened 2017-09-14 20:35 UTC
From recent experiments with crete, I found the transmission of trace between vm-node to dispatch can be a bottleneck for the whole workflow of dispatch (crete-manager). Here are an example of dispatch's output that implies this bottleneck.

      time (s)|  tests left| traces left|  1-[vm] tc/tr| 2-[svm] tc/tr|
          1932|      0/1844|      1/1401|         0/442|           0/0|

From the output above, there are 442 traces from vm-node waiting to be transmitted to dispatch, while the backend is idle because of no available traces to replay. 

From the current implementation of [dispatch](https://github.com/SVL-PSU/crete-dev/blob/71ab5f8f3c6116e1024219d6b93190102c956584/lib/cluster/dispatch.cpp#L634), there is at most one trace can be transmitted from vm-node to dispatch for one iteration of dispatch's FSM cycle.

**Comment by moralismercatus** [comment] 2017-09-15 23:25
This sounds very familiar. I'm sure I've encountered something similar before.

I can't think of a reason that there should be a restriction that only one trace be transmitted at each iteration, but I'm not sure that's the only factor at play here.

What I find curious about this situation is that, based on the report, it appears that traces can be generated faster than they can be transferred. Presumably, it should be faster for file transfer of the trace than all the overhead of tracing. Then again, maybe I'm not account for something.

For what it's worth, transferring more than one trace should be rather straightforward, and done entirely in Dispatch. Rather than a single call to receive_trace, in the RxTrace state: _for 0..vm_trace_multiplier: receive_trace() ..._ In addition, VMNodeFSM_::trace_ would need to become VMNodeFSM_::traces_, down the line to handle a collection over a single trace.

I do wonder, though, if it's not more the issue with thread contention discussed in #23 . In short, the dispatch communication thread in crete-vm-node is being starved in favor of the QEMU thread, so while QEMU is executing, traces aren't being transferred as they should be.

My suggestion is to implement something similar to the fix in #23 first, as it's an outstanding issue in any case, and see if further work needs to be done. Let me know if the fix needs further explanation.

**Comment by likebreath** [comment] 2017-09-16 00:02
@moralismercatus Thanks for the constructive inputs.

I agree that the thread contention issue could be a bigger factor. Can you put up a patch to the main code base from your fix on your branch? Ideally, you can make a pull request to fix the issue. I can see the contention may affect the whole workflow a lot.

For transferring more than one trace, besides the change in dispatch, will it require changes on svm-node? As the transmission of trace from dispatch to svm-node are now one trace per transaction. Or would you think it wouldn't be necessary?

**Comment by moralismercatus** [comment] 2017-09-18 17:13
I can put in a pull request, as soon as I can.

I don't think it will require changes in svm-node, aside from NodeDriver (used by both vm-node and svm-node), as transmission is initiated by dispatch.

**Comment by moralismercatus** [comment] 2017-09-22 22:32
The mentioned fix, when applied to this branch, appears to cause a deadlock. I'll have to root cause it. Will take a little longer than I expected.

**Comment by likebreath** [comment] 2017-09-22 23:17
@moralismercatus Thanks for the effort. We can find a common time to do pair-programming on this issue if you think it is a good idea. 

I did few changes to the workflow of dispatch (move translation from svm-node to vm-node, etc), although I don't think those changes should make any differences.

**Comment by moralismercatus** [comment] 2017-09-26 20:22
@likebreath I rethought the fix. Rather than waiting for the transmission to finish, in order to prevent the run-node thread from monopolizing the shared resource, I simply yield the thread's CPU time slice. I think this is a better solution anyway. See the pull request comments.

PS. I never root caused the deadlock, but it's conceivable there's some dependency between the a request and the run-node thread.

**Comment by likebreath** [comment] 2017-09-26 22:18
> I rethought the fix. Rather than waiting for the transmission to finish, in order to prevent the run-node thread from monopolizing the shared resource, I simply yield the thread's CPU time slice. I think this is a better solution anyway. See the pull request comments.

I tested your patch in #35 on my side, and I believe the bottleneck issue are mainly mitigated, based on couple of experiments. So I will close this issue. Thanks for the work. @moralismercatus

**Closed as completed** 2017-09-26 22:18 UTC
Labels: enhancement
